services:
  # War Room 3.0 UI - React Frontend with Builder.io Integration
  - type: web
    name: war-room-3-ui
    runtime: static
    plan: free
    
    # Build command - Install dependencies and build React app
    buildCommand: npm install && npm run build
    
    # Static files location after build
    staticPublishPath: ./dist
    
    # SPA routing - redirect all routes to index.html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
    # Environment Variables
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      
    # Auto-deploy from GitHub
    repo: https://github.com/Think-Big-Media/3.0-ui-war-room
    branch: main
    autoDeploy: true
    
    # Security Headers
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
